//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TANEGRINE_ZIP {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TANEGRINE_ZIP.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 TZIP is still doing some job,please wait untill the task completed 的本地化字符串。
        /// </summary>
        internal static string AlreadyDoingJob {
            get {
                return ResourceManager.GetString("AlreadyDoingJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 compress file 的本地化字符串。
        /// </summary>
        internal static string CompressFile {
            get {
                return ResourceManager.GetString("CompressFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 compress 的本地化字符串。
        /// </summary>
        internal static string compressText {
            get {
                return ResourceManager.GetString("compressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 an error occurred 的本地化字符串。
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 extract all directly 的本地化字符串。
        /// </summary>
        internal static string extractDirectlyALLText {
            get {
                return ResourceManager.GetString("extractDirectlyALLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 extract selected directly 的本地化字符串。
        /// </summary>
        internal static string extractDirectlySELECTEDText {
            get {
                return ResourceManager.GetString("extractDirectlySELECTEDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TZIP extracting failed 的本地化字符串。
        /// </summary>
        internal static string ExtractFailedText {
            get {
                return ResourceManager.GetString("ExtractFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting 的本地化字符串。
        /// </summary>
        internal static string ExtractingText {
            get {
                return ResourceManager.GetString("ExtractingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 extract 的本地化字符串。
        /// </summary>
        internal static string extractText {
            get {
                return ResourceManager.GetString("extractText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 extract selected to a folder 的本地化字符串。
        /// </summary>
        internal static string extractToAFolderSELECTEDText {
            get {
                return ResourceManager.GetString("extractToAFolderSELECTEDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 extract all to a folder 的本地化字符串。
        /// </summary>
        internal static string extractToFolderALLText {
            get {
                return ResourceManager.GetString("extractToFolderALLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 image file 的本地化字符串。
        /// </summary>
        internal static string ImageFile {
            get {
                return ResourceManager.GetString("ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 home 的本地化字符串。
        /// </summary>
        internal static string mainTabText {
            get {
                return ResourceManager.GetString("mainTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 haven&apos;t open a file yet 的本地化字符串。
        /// </summary>
        internal static string NoOpenedFile {
            get {
                return ResourceManager.GetString("NoOpenedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not a compressed file 的本地化字符串。
        /// </summary>
        internal static string NotACompressedFile {
            get {
                return ResourceManager.GetString("NotACompressedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opening the file... 的本地化字符串。
        /// </summary>
        internal static string OpeningFile {
            get {
                return ResourceManager.GetString("OpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string openText {
            get {
                return ResourceManager.GetString("openText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ready 的本地化字符串。
        /// </summary>
        internal static string readytext {
            get {
                return ResourceManager.GetString("readytext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 extract to 的本地化字符串。
        /// </summary>
        internal static string SelectExtractFolderText {
            get {
                return ResourceManager.GetString("SelectExtractFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 settings 的本地化字符串。
        /// </summary>
        internal static string settingsText {
            get {
                return ResourceManager.GetString("settingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 uninstall the file(not delete) 的本地化字符串。
        /// </summary>
        internal static string uninstallFileText {
            get {
                return ResourceManager.GetString("uninstallFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 uninstalling the file... 的本地化字符串。
        /// </summary>
        internal static string UninstallingText {
            get {
                return ResourceManager.GetString("UninstallingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknow File 的本地化字符串。
        /// </summary>
        internal static string UnknowFile {
            get {
                return ResourceManager.GetString("UnknowFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of loaded file is unsupported 的本地化字符串。
        /// </summary>
        internal static string UnknownFileType {
            get {
                return ResourceManager.GetString("UnknownFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of loaded file is unsupported(E1) 的本地化字符串。
        /// </summary>
        internal static string UnknownFileTypeE1 {
            get {
                return ResourceManager.GetString("UnknownFileTypeE1", resourceCulture);
            }
        }
    }
}
