<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>TANEGRINE_ZIP</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>655049f4-4e69-449c-824a-293a9573c864</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageReference Include="SharpCompress" Version="0.50.1" />
    <PackageReference Include="System.IO.Compression" Version="4.3.0" />
    <PackageReference Include="UnrarNative" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="LanguageResource.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="LanguageResource.zh-CN.resx">
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

</Project>